development:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USER') { Ahmed } %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  pool: 5
  database: company_management_development

test:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USER') { Ahmed } %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  pool: 5
  database: company_management_test

production:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USER') { Ahmed } %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  pool: 5
  database: company_management_production
